[tool.poetry]
name = "deps-report"
version = "0.1.0"
description = ""
authors = ["Corentin Garcia <cgarcia@meilleursagents.com>"]

[tool.poetry.scripts]
deps-report = "deps_report.main:main"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
colorama = "^0.4.4"
beautifulsoup4 = "^4.9.3"
requests = "^2.25.1"
packaging = "^20.9"
tabulate = "^0.8.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.8.0"
black = "^20.8b1"
mypy = "^0.812"
flake8 = "^3.9.1"
flake8-docstrings = "^1.6.0"
pyproject-flake8 = "^0.0.1-alpha.2"
pdbpp = "^0.10.2"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.flake8]
max_line_length = 88
extend-ignore = "D100,D101,D104,E501"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
