[tool.poetry]
name = "deps-report"
version = "0.2.0"
description = ""
authors = ["Corentin Garcia <cgarcia@meilleursagents.com>"]

[tool.poetry.scripts]
deps-report = "deps_report.main:main"

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.7.4"
beautifulsoup4 = "^4.9.3"
click = "^8"
colorama = "^0.4.4"
packaging = "^20.9"
PyGithub = "^1.55"
tabulate = "^0.8.9"
toml = "^0.10.2"
urllib3 = "^1.26.5"

[tool.poetry.dev-dependencies]
black = "^21.5b2"
flake8 = "^3.9.2"
flake8-docstrings = "^1.6.0"
isort = "^5"
mypy = "^0.900"
pdbpp = "^0.10.2"
pyproject-flake8 = "^0.0.1a2"
pytest = "^6"
types-tabulate = "*"
types-toml = "*"

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.flake8]
max_line_length = 88
extend-ignore = "D100,D101,D104,E501"
per-file-ignores = "__init__.py:F401"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
