name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name:  CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: pip install poetry
      - name: Setup environment
        run: poetry install
      - name: Style
        run: make style
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: meilleursagentstech/deps-report:latest
